export const mockOffersData = [
  {
    id: 1,
    number: "01",
    title: "Frontend",
    subtitle: "beginner",
    discount: true,
    hashCode: "FD:0001",
    image: "/bird-thumbnail.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt, blanditiis dicta. Accusantium voluptatibus ea doloremque itaque recusandae dolores placeat laboriosam dicta velit fugiat enim praesentium qui aperiam.",
    level: "trainee / junior",
    price: 200,
    mentor: "Ivan Ivanov",
    mentorExperiance: 4,
    duration: 4,
    linkedinLink: "",
  },
  {
    id: 2,
    number: "02",
    title: "Frontend",
    subtitle: "advanced",
    discount: false,
    hashCode: "FD:0002",
    image: "/bird-thumbnail.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt, blanditiis dicta. Accusantium voluptatibus ea doloremque itaque recusandae dolores placeat laboriosam dicta velit fugiat enim praesentium qui aperiam. Deserunt, blanditiis dicta. Accusantium voluptatibus ea doloremque itaque recusandae dolores placeat laboriosam dicta velit fugiat enim praesentium qui aperiam.",
    level: "junior / middle",
    price: 200,
    mentor: "Yauheni Bykovski",
    mentorExperiance: 6,
    duration: 4,
    linkedinLink: "https://www.linkedin.com/in/eugenibykovski/",
  },
  {
    id: 3,
    number: "03",
    title: "Backend",
    subtitle: "advanced",
    discount: false,
    hashCode: "BD:0002",
    image: "/bird-thumbnail.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt, blanditiis dicta. Accusantium voluptatibus ea doloremque itaque recusandae dolores placeat laboriosam dicta velit fugiat enim praesentium qui aperiam. Deserunt, blanditiis dicta. Accusantium voluptatibus ea doloremque itaque recusandae dolores placeat laboriosam dicta velit fugiat enim praesentium qui aperiam.",
    level: "junior / middle",
    price: 200,
    mentor: "Mark Ivanov",
    mentorExperiance: 4,
    duration: 4,
    linkedinLink: "",
  },
  {
    id: 4,
    number: "04",
    title: "Backend",
    subtitle: "beginner",
    discount: false,
    hashCode: "BD:0001",
    image: "/bird-thumbnail.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt, blanditiis dicta. Accusantium voluptatibus ea doloremque itaque recusandae dolores placeat laboriosam dicta velit fugiat enim praesentium qui aperiam. Deserunt, blanditiis dicta. Accusantium voluptatibus ea doloremque itaque recusandae dolores placeat laboriosam dicta velit fugiat enim praesentium qui aperiam.",
    level: "trainee / junior",
    price: 200,
    mentor: "Yauheni Bykovski",
    mentorExperiance: 6,
    duration: 4,
    linkedinLink: "https://www.linkedin.com/in/eugenibykovski/",
  },
  {
    id: 5,
    number: "05",
    title: "DevOps",
    subtitle: "advanced",
    discount: true,
    hashCode: "DO:0002",
    image: "/bird-thumbnail.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt, blanditiis dicta. Accusantium voluptatibus ea doloremque itaque recusandae dolores placeat laboriosam dicta velit fugiat enim praesentium qui aperiam. Deserunt, blanditiis dicta. Accusantium voluptatibus ea doloremque itaque recusandae dolores placeat laboriosam dicta velit fugiat enim praesentium qui aperiam.",
    level: "junior / middle",
    price: 200,
    mentor: "Anatoli Semenov",
    mentorExperiance: 8,
    duration: 4,
    linkedinLink: "",
  },
  {
    id: 6,
    number: "06",
    title: "PM",
    subtitle: "advanced",
    discount: false,
    hashCode: "PM:0001",
    image: "/bird-thumbnail.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt, blanditiis dicta. Accusantium voluptatibus ea doloremque itaque recusandae dolores placeat laboriosam dicta velit fugiat enim praesentium qui aperiam. Deserunt, blanditiis dicta. Accusantium voluptatibus ea doloremque itaque recusandae dolores placeat laboriosam dicta velit fugiat enim praesentium qui aperiam.",
    level: "junior / middle",
    price: 200,
    mentor: "Kate Bykovskaya",
    mentorExperiance: 4,
    duration: 4,
    linkedinLink: "https://www.linkedin.com/in/eugenibykovski/",
  },
  {
    id: 7,
    number: "07",
    title: "Frontend",
    subtitle: "advanced",
    discount: false,
    hashCode: "FD:0002",
    image: "/bird-thumbnail.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt, blanditiis dicta. Accusantium voluptatibus ea doloremque itaque recusandae dolores placeat laboriosam dicta velit fugiat enim praesentium qui aperiam. Deserunt, blanditiis dicta. Accusantium voluptatibus ea doloremque itaque recusandae dolores placeat laboriosam dicta velit fugiat enim praesentium qui aperiam.",
    level: "junior / middle",
    price: 200,
    mentor: "Yauheni Bykovski",
    mentorExperiance: 6,
    duration: 4,
    linkedinLink: "https://www.linkedin.com/in/eugenibykovski/",
  },
  {
    id: 8,
    number: "08",
    title: "Frontend",
    subtitle: "advanced",
    discount: false,
    hashCode: "FD:0002",
    image: "/bird-thumbnail.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt, blanditiis dicta. Accusantium voluptatibus ea doloremque itaque recusandae dolores placeat laboriosam dicta velit fugiat enim praesentium qui aperiam. Deserunt, blanditiis dicta. Accusantium voluptatibus ea doloremque itaque recusandae dolores placeat laboriosam dicta velit fugiat enim praesentium qui aperiam.",
    level: "junior / middle",
    price: 200,
    mentor: "Yauheni Bykovski",
    mentorExperiance: 6,
    duration: 4,
    linkedinLink: "https://www.linkedin.com/in/eugenibykovski/",
  },
];
